[package]
name = "gomoku"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12.1", features = ["highlighter"] }
rand = "0.8.5"
tokio = { version = "1.39.2", features = ["full"] }
